

-- COMO TRABAJAR CON LOS OPERADORES DE CONJUNTO SI LOS REGISTRO DE LAS TABLAS NO COINSIDEN 
--CON EL TIPO DE DATOS QUE TENIAN QUE SER

        SELECT EMPLOYEE_ID,JOB_ID,SALARY
        FROM EMPLOYEES
        UNION 
        SELECT EMPLOYEE_ID,JOB_ID,0-- COMO NO EXISTE EL CAMPO SOLO SE COLOCA UN DATO DEL MISMO TIPO DE DATOS
        FROM JOB_HISTORY;
        
--        OTRO EJEMPLO
-- COMO EL CAMPO DEPARTMENT NAME NO EXISTE EN LA TABLA LOCATION SE SUSTITUYE CON UN DATO DEL MISMO TIPO DE DATOS QUE LA TABLA DESTINO
        SELECT LOCATION_ID,DEPARTMENT_NAME DEPARTAMENTO , TO_CHAR(NULL) "LOCALIZACION DEPOSITO"
        FROM DEPARTMENTS
        UNION
        SELECT LOCATION_ID,TO_CHAR(NULL)"DEPARTAMENTO",STATE_PROVINCE
        FROM LOCATIONS;