

        /*DELETE ELIMINA LOS REGISTROS DE UNA TABLA*/
        
        --PARA ELIMINAR SOLO LAS DECIADAS SIEMPRE SE COLOCA LA CLAUSULA WHERE
        DELETE FROM DEPARTMENTS
        WHERE DEPARTMENT_NAME='CRE_EMP';
        
        SELECT DEPARTMENT_NAME 
        FROM DEPARTMENTS
        WHERE DEPARTMENT_NAME='CRE_EMP';
        
        
        --DELETE SIN WHERE
        SELECT * FROM SALES_REPS;
        --SE ELIMINAN TODOS LOS REGISTROS DE LA TABLA
        DELETE FROM SALES_REPS;
        
        --OTRO EJEMPLO
        
        SELECT * FROM DEPARTMENTS
        WHERE UPPER(DEPARTMENT_NAME)LIKE('%PUBLIC%');
        
        DELETE FROM COPY_EMP
        WHERE DEPARTMENT_ID IN(SELECT DEPARTMENT_ID FROM DEPARTMENTS
                                WHERE UPPER(DEPARTMENT_NAME)LIKE '%PUBLIC%');
        SELECT * FROM COPY_EMP;
        
        --OTRO MANERA DE BORRAR TODOS LOS REGISTROS ES UTILIZANDO EL TRUNCATE TABLE 
        --ESTE FORMATE TODA LA TABLA
        
        --TRUNCATE TABLE
        
        TRUNCATE TABLE COPY_EMP;
        
        SELECT * FROM COPY_EMP;