

--INSERTAR CON LA SUSTITUCION DE VARIABLE (PROMPT)

    INSERT INTO DEPARTMENTS
                (DEPARTMENT_ID,DEPARTMENT_NAME,LOCATION_ID)
    VALUES
                (&DEPARTMENT_ID,'&DEPARTMENT_NAME',&LOCATION_ID);--DE ESTE MODO PODEMOS IR INGRESANDO LOS REGISTROS DE UNO EN UNO
                --EN UNA VENTA MODAL SOLO HAY QUE TENER CUIDADO CON EL TIPO DE DATO QUE INGRESEMOS
                
                SELECT * FROM DEPARTMENTS;
                
        --INSERT DESDE OTRO TABLA COMO PASAR LOS REGISTROS
        
        CREATE TABLE SALES_REPS(
        ID NUMBER(6),
        NAME VARCHAR2(25),
        SALARY NUMBER(8,2),
        COMMISSION_PCT NUMBER(2,2)
        );
        
        INSERT INTO SALES_REPS 
                        (ID,NAME,SALARY,COMMISSION_PCT)
        SELECT EMPLOYEE_ID,LAST_NAME,SALARY,COMMISSION_PCT
        FROM EMPLOYEES
        WHERE JOB_ID LIKE '%REP%';
        
        SELECT * FROM SALES_REPS;