

--        CREACION DE INDICE EN LAS TABLAS

CREATE INDEX EMP_NAME_INDEX
ON EMPLOYEES(LAST_NAME);

-- UN INDEX NO PUEDE SER MODIFICADO SI QUIERE MODIFICARLO TIENE QUE ELIMINAR EL ACTUAL Y HACERLO  NUEVAMENTE

DROP INDEX EMP_NAME_INDEX;