

        -- SECUENCIAS EN ORACLE 
        
        CREATE SEQUENCE PLUS
        INCREMENT BY 10
        START WITH 520
        MAXVALUE 9999
        NOCACHE
        NOCYCLE;
        
        INSERT INTO DEPARTMENTS(DEPARTMENT_ID,DEPARTMENT_NAME,LOCATION_ID)
        VALUES(PLUS.NEXTVAL,'PRUEVA 5',2500);
        
        SELECT * FROM DEPARTMENTS
        ORDER BY DEPARTMENT_ID DESC;
        
        SELECT PLUS.NEXTVAL FROM DUAL;
        
--        CAMBIAR EL VALOR DEL ACTO INCREMENTI

ALTER SEQUENCE PLUS
INCREMENT BY 20;

DROP SEQUENCE PLUS;