

-- estamos en la ultima etapa de el curso de SQL Oracle 

-- Otros objetos de esquemas

--Creacion de vistas

        CREATE VIEW EMPVU80 AS
        SELECT EMPLOYEE_ID,LAST_NAME,SALARY
        FROM EMPLOYEES
        WHERE DEPARTMENT_ID = 70;
        
        DESC EMPVU80;
        SELECT * FROM EMPVU80;
--        LA VISTA MUESTRA LOS DATOS MAS EL SU INTERIOR NO ALMACENA DATOS SOLO LOS MUESTRA
-- SIEMPRE TIENE QUE IR EL AS EN UNA VISTA
        
        CREATE VIEW TEMPORAL80
        AS
        SELECT EMPLOYEE_ID,LAST_NAME,SALARY 
        FROM EMPLOYEES
        WHERE DEPARTMENT_ID=80;
        
        CREATE VIEW SALUV50
        AS
        SELECT EMPLOYEE_ID AS CODIGO,SALARY * 12 AS "SALARIO ANUAL"
        FROM EMPLOYEES
        WHERE DEPARTMENT_ID = 50;

-- DDL PARA CREAR O REEMPLAZAR LA VISTA QUE YA ESTABA CREADA
        DESC EMPVU80;
        --CREAT O REEMPLAZAR
        CREATE OR REPLACE VIEW EMPVU80
        (ID_NUMBER,NAME,SAL,DEPARTMENT_ID)
        AS
        SELECT EMPLOYEE_ID,FIRST_NAME||' '||LAST_NAME,SALARY,DEPARTMENT_ID
        FROM EMPLOYEES
        WHERE DEPARTMENT_ID = 80;
        
        DESC EMPVU80;