

        /*CREATE SUB QUERRYS*/
        
        --CREANDO UNA TABLA APARTIR DE OTRA TABLA POR MEDIO DE SUB CONSULTAS
        
        SELECT * FROM EMPLOYEES;
        
        CREATE TABLE TEMP_EMP
        AS 
        SELECT  EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,SALARY*10 AS "SALARIO ANUAL"
        FROM EMPLOYEES
        WHERE DEPARTMENT_ID =80;
        
        SELECT * FROM TEMP_EMP;
        DESCRIBE TEMP_EMP;
        
        ALTER TABLE TEMP_EMP READ ONLY;--COLOCANDO LA TABLA SOLO DE LECTURA
        
        SELECT * FROM TEMP_EMP;
        --PARA COLOCAR DE NUEVO UNA TABLA SE VE COLOCAR EN ESCRITURA Y E\LECTURA
        ALTER TABLE TEMP_EMP READ WRITE;
        
        DELETE FROM TEMP_EMP
        WHERE EMPLOYEE_ID =145;