


        /*CONTRAINT FOREIGN KEY
        POR MEDIO DE ESTE CONSTRAIN Y POR MEDIO DE LA LLLAVE PRIMARIA ES COMO SE RELACIONAN DOS O MAS TABLAS*/
        
        --TABLA PADRE
        CREATE TABLE PROVEEDOR
        (
        ID_PRO number(6) PRIMARY KEY,
        NOMBRE VARCHAR(20) NOT NULL,
        APELLIDO VARCHAR(20) DEFAULT 'SIN APELLIDO',
        SALARIO NUMBER(8,2)
        );
        
        CREATE TABLE VENDEDOR
        (
        ID_VENTAS number(6)UNIQUE,
        ID_PRO number(6) NOT NULL,
        CONSTRAINT PK_VENDEDOR_PROVEEDOR--AQUI ES DONDE NOSOTROS RELACIONAMOS NUESTRA TABLA
        FOREIGN KEY(ID_PRO)
        REFERENCES PROVEEDOR(ID_PRO)
        );
        
        DESCRIBE PROVEEDOR;
        INSERT INTO PROVEEDOR
        VALUES(1,'ALLAN','SANCHEZ',100);
        
        INSERT INTO PROVEEDOR
        VALUES(2,'FATIMA','LEMUZ',1000);
        INSERT INTO PROVEEDOR
        VALUES(3,'PEDRO','DISCORDIA',100);
        
        DESCRIBE VENDEDOR;
        INSERT INTO VENDEDOR
        VALUES(01,1);
        
        
        INSERT INTO VENDEDOR
        VALUES(02,2);
        
        INSERT INTO VENDEDOR
        VALUES(03,2);
        
        INSERT INTO VENDEDOR
        VALUES(05,3);
        
        SELECT * FROM PROVEEDOR;
        
        SELECT * FROM VENDEDOR;