

        /*CONTRAINT UNIQUE*/
        
        
        --UNIQUE SE LO DEBEMOS COLOCAR CUANDO QUEREMOS QUE NUESTRO CAMPO SEA UNICO QUE EN TODA LA TABLA NO SE VA A REPETIR
        
        CREATE TABLE  EEE(
        EEE_ID number(6),
        COL_A VARCHAR(20)NOT NULL,
        COL_B VARCHAR(20) UNIQUE
        );
        
        INSERT INTO EEE
        VALUES(1,'SIN NULLOS',1);
        
        INSERT INTO EEE
        VALUES(2,'VALOR',2);
        
        --SI EL TIPO DE DATO DONDE DEFINIMOS EL UNIQUE ES NUMBRE ESTA SI VA A ACEPTAR VALORIOS VALORES NULL
        
        INSERT INTO EEE
        VALUES(3,'PROVANDO',NULL);
        
        SELECT * FROM EEE;
        
        --OTRO CONSTRAINT ES CHECK
        
        --CHECK SE USA PARA QUE A LA HORA DE UN INGRESO ESTE CHEQUE  CIERTA CONDICION LA CUAL NOSOTROS LE INDIQUEMOS
        
        CREATE TABLE FFF(
        FFF_ID number(6) PRIMARY KEY,
        COL_A VARCHAR(20) NOT NULL,
        SALARY number(6) CHECK(SALARY>100)--CONDICION QUE SIEMPRE VERIFICA ANTES DE HACER EL INGRESO DE LOS REGISTROS
        );
        
        INSERT INTO FFF
        VALUES(1,'DOS',101);
        
        INSERT INTO FFF
        VALUES(2,'TRES',102);
        
        SELECT * FROM FFF;